on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "blog-rust" #Must be unique in Heroku
          heroku_email: "djkde.co@gmail.com"
          usedocker: true
      - uses: grafana/k6-action@v0.2.0
        with:
          filename: tests/stress.js
